#!/usr/bin/python3

import webbrowser
import sys
#from pathlib import Path
import json
import os.path

argv = sys.argv
argc = len(argv)

option = argv[1]
if(option=='--add' or option=='-a'):
    topic = argv[2]
    subtopic = argv[3]
    links = argv[4:]
    if not os.path.isfile("%s.json"%topic):
        # topic doesn't exist , create a topic file
        with open("%s.json"%topic, mode='w', encoding='utf-8') as f:
            obj = {}
            json.dump(obj,f)

    with open("%s.json"%topic, mode='r', encoding='utf-8') as f:
        entries = json.load(f)
    if subtopic not in entries:
        entries[subtopic] = links
    else:
        entries[subtopic] += links

    with open("%s.json"%topic, mode='w', encoding='utf-8') as f:
        json.dump(entries,f)

if(option == '--load' or option == '-l'):
    topic = argv[2]
    subtopic = argv[3]
    with open("%s.json"%topic, mode='r', encoding='utf-8') as f:
        entries = json.load(f)
    for link in entries[subtopic]:
        webbrowser.open(link)